version: '3.8'
services:
  docker-mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: 105
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - app-network
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      docker-mysql:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: docker-mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 1234
    ports:
      - "8080:80"
    depends_on:
      - docker-mysql
    networks:
      - app-network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge